apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
resources:
- ../../../../common/gotk-components.yaml
- ../../../../common/gotk-sync.yaml
