# common/gotk-sync.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flux-system
  namespace: flux-system
type: Opaque
data:
  # token do repozytorium Git itp.
  # Przykład:
  # github_token: <base64-encoded-token>
